apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: gitops-stage
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/catalog-4-12@sha256:29b55b56edb2e66d143e2313394689df30c881f4a0d2f489d15126a026547753
  displayName: Konflux FBC test CatalogSource
  publisher: Red Hat